// Project data for the Projects section.
// Kept separate from the UI component so content can be updated
// without touching any rendering/markup logic.

export const projects = [
  {
    id: 1,
    title: "BuyNest",
    subtitle: "E-Commerce Platform",
    image: "/projects/project-1/buynestFull.png",
    images: [
      "/projects/project-1/project-5-image-1.png",
      "/projects/project-1/project-5-image-2.png",
      "/projects/project-1/project-5-image-3.png",
      "/projects/project-1/project-5-image-4.png",
      "/projects/project-1/project-5-image-5.png",
      "/projects/project-1/project-5-image-6.png",
      "/projects/project-1/project-5-image-7.png",
    ],
    description:
      "A full-stack MERN e-commerce platform with secure authentication, AI-powered support, and integrated online payments.",

    overview:
      "BuyNest is a modern e-commerce platform designed to provide customers with a secure, fast, and user-friendly online shopping experience. The platform enables users to browse products, manage shopping carts, complete secure SSLCommerz payments, and download PDF invoices. Administrators have dedicated dashboards for managing products, users, and orders, while an AI-powered Gemini chatbot enhances customer support and engagement.",

    highlights: [
      "Secure checkout with SSLCommerz payment integration",
      "Role-based dashboards for customers and administrators",
      "AI-powered chatbot using Gemini API",
      "Automatic PDF invoice generation",
      "Product, order, and user management",
      "Admin control panel for platform management",
      "User authentication and authorization",
      "Responsive design for all screen sizes",
    ],

    tags: [
      "React",
      "Tailwind CSS",
      "Firebase Authentication",
      "Express.js",
      "MongoDB",
      "Gemini API",
      "SSLCommerz",
      "JWT",
      "Leaflet",
      "PDF Generation",
      "LottieFiles",
      "TanStack Query",
      "Recharts",
      "React Hook Form",
      "React Router",
      "React Toastify",
      "Leaflet Routing Machine",
      "Framer motion",
    ],
    liveUrl: "https://tools-final-projectt.web.app/",
    githubUrl: "https://github.com/MasadRayan/Tools-Final-project-client",
    // Optional extras
    duration: "1 Month",
    team: "Solo Project",
    role: "Full Stack Developer",

    span: "lg:col-span-7",
  },
  {
    id: 2,
    title: "Skill Nova",
    subtitle: "E-Learning Platform",
    image: "/projects/project1Full.png",
    images: [
      "/projects/project1.png",
      "/projects/project-2/project-2-image-2.png",
      "/projects/project-2/project-2-image-3.png",
      "/projects/project-2/project-2-image-4.png",
      "/projects/project-2/project-2-image-5.png",
      "/projects/project-2/project-2-image-6.png",
      "/projects/project-2/project-2-image-7.png",
    ],
    description:
      "A complete MERN stack e-learning platform with role-based dashboards for students, instructors, and admins. Students can browse courses, enroll, submit assignments, and track progress.",

    overview:
      "Skill Nova is a proper LMS built to connect students and instructors in one streamlined space. Students can explore available courses, enroll with a click,student can pay to enroll and can download the reciept of payment. They submit assignments, and track their learning progress in real time. Instructors get tools to publish courses and manage submissions, while admins oversee the platform through a dedicated control panel.",

    tags: [
      "React",
      "TailwindCSS",
      "Firebase Auth",
      "MongoDB",
      "Express.js",
      "Stripe",
      "React Hook Form",
      "TanStack Query",
      "React Router",
      "React Toastify",
      "React PDF",
      "LottieFiles",
      "GSAP",
      "Framer motion",
      "React Icons",
      "Leaflet",
      "JWT",
      "Axios",
    ],
    liveUrl: "https://skill-nova-app.web.app/",
    githubUrl: "https://github.com/MasadRayan/SkillNova-Client",
    span: "lg:col-span-5",
    highlights: [
      "Real-time course management for instructors",
      "Secured Payment integration for course enrollment with stripe",
      "Dedicated dashboards for students, instructors, and admins",
      "Assignment submission and progress tracking for students",
      "Responsive UI for learning on any device",
      "Admin control panel for platform management",
    ],

    duration: "3.5 Weeks",
    team: "Solo Project",
    role: "Full Stack Developer",
  },
  {
    id: 3,
    title: "Book Koro",
    subtitle: "Hotel Management Platform",
    image: "/projects/project-3/project2Full.png",
    images: [
      "/projects/project-3/project2.png",
      "/projects/project-3/project-3-image-2.png",
      "/projects/project-3/project-3-image-3.png",
      "/projects/project-3/project-3-image-4.png",
      "/projects/project-3/project-3-image-5.png",
    ],
    description:
      "A complete MERN stack hotel management platform with dashboards for guests,  and admins. This supports hotel search, booking, occupancy tracking, payment integration.",
    overview:
      "Book Koro is a complete hotel management platform designed to streamline the entire booking process. Guests can easily search for available rooms, view details, and make reservations. Hotel managers have access to powerful tools for managing room inventories, setting prices, and tracking occupancy rates. Admins can oversee all operations through a centralized control panel.",
    tags: [
      "React",
      "Firebase Auth",
      "MongoDB",
      "Express.js",
      "Swiper",
      "Marquee",
      "AOS",
      "Framer Motion",
      "GSAP",
      "Daisy UI",
      "Leaflet",
      "Leaflet Routing Machine",
      "JWT",
    ],
    liveUrl: "https://bookoro-app.web.app/",
    githubUrl: "https://github.com/MasadRayan/Bookoro-Client",
    span: "lg:col-span-5",
    highlights: [
      "Real-time room availability and booking updates",
      "Filter and search for available rooms",
      "Hotel manager tools for pricing and occupancy",
      "Live review of rooms",
      "Streamlined admin operations for bookings and users",
      "Responsive UI for learning on any device",
    ],
    duration: "2.5 Weeks",
    team: "Solo Project",
    role: "Full Stack Developer",
  },
  {
    id: 4,
    title: "Hobby Hive",
    subtitle: "Hobby Groups Platform",
    image: "/projects/project-4/project5Full.png",
    images: [
      "/projects/project-4/project4.png",
      "/projects/project-4/project-4-image-2.png",
      "/projects/project-4/project-4-image-3.png",
      "/projects/project-4/project-4-image-4.png",
      "/projects/project-4/project-4-image-5.png",
    ],
    description:
      "HobbyHive is a full-stack MERN platform that helps people discover and manage their hobby groups. It includes secure authentication, group creation, updates, and interactive community features.",
    overview:
      "HobbyHive is a comprehensive platform for hobby enthusiasts to discover, join, and manage their interest groups. It provides a seamless experience for creating and interacting with hobby communities. With secure authentication, group creation, updates, and interactive community features, HobbyHive empowers users to connect and share their passions with a vibrant community. The platform also includes a dark mode option for a personalized and engaging experience.",
    tags: [
      "React",
      "Firebase Auth",
      "TailwindCSS",
      "MongoDB",
      "Express.js",
      "Swiper",
      "Marquee",
      "AOS",
      "Framer Motion",
      "GSAP",
      "Daisy UI",
      "Leaflet",
      "Leaflet Routing Machine",
      "JWT",
    ],
    liveUrl: "https://tangerine-crostata-f1e467.netlify.app/",
    githubUrl: "https://github.com/MasadRayan/HobbyHive-Client",
    span: "lg:col-span-7",
    highlights: [
      "Create, join, update, and delete hobby groups",
      "Google and GitHub authentication options",
      "Responsive UI for learning on any device",
      "Interactive community features",
      "Responsive community experience with dark/light mode",
    ],
    duration: "1.5 Weeks",
    team: "Solo Project",
    role: "Full Stack Developer",
  },
];