import { Inter, Funnel_Display } from "next/font/google";
import "./globals.css";


const funnel = Funnel_Display({
  variable: "--font-funnel",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${funnel.variable} antialiased funnel-display`}
      >
        {children}
      </body>
    </html>
  );
}
